### ISSUE TITLE
Share Deep Learning Models online

### ISSUE THREAD

**Issue by virajprabhu** [Cloud-CV/GSoC-Ideas#1]
**Project Title**: Share Deep Learning Models online

**Description**: One of the problems facing young researchers who want to learn more about deep learning models is the amount of effort it takes to learn these new frameworks. [Here](https://docs.google.com/spreadsheets/d/1XvGfi3TxWm7kuQ0DUqYrO6cxva196UJDxKTxccFqb9U/edit#gid=0) is a small list of 64 deep learning frameworks that are available. Each framework is good at different purposes. The goal of this project is to provide an online platform for trying deep learning algorithms / models that will reduce the barrier of entry to the world of deep learning and applications in computer vision. 

In GSoC '16, @gauravgupta22 built the first version of Fabrik, a platform to build deep-learning models via a simple drag-and-drop interface. As of today, we support export to model definition files of widely popular deep learning frameworks like TensorFlow, Caffe and Keras, as well as the ability to import and visualize models developed in these frameworks.

Our next goal is become a _collaborative_ platform, where students and researchers can have model discussions, and collaboratively build and edit models in real time

- Model Sharing (see [#17).](https://github.com/Cloud-CV/IDE/issues/17)
- Layer boxes UI Enhancements (see [#16](https://github.com/Cloud-CV/IDE/issues/16))
- Switch from scroll to zoom in canvas to vertical scrolling (see [#14](https://github.com/Cloud-- CV/IDE/issues/14))
- Write unittests (see [#7](https://github.com/Cloud-CV/IDE/issues/7))

**Deliverable**: the issues mentioned above should be implemented by the end of the GSoC period. Moreover, we expect students to also have implemented other improvements that they have proposed.

As an additional goal, we want to add support for PyTorch which is another widely popular deep learning framework. 

**Mentor**: Viraj Prabhu @virajprabhu, Deshraj Yadav @deshraj, Harsh Agrawal @dexter1691

**Co-Mentor**: Shiv Baran Singh @spyshiv 

**Skills**: ReactJS, Python, Django, familiarity with deep learning a plus (but not essential)

**Skill Level**: Medium

**Get started**: Take a look at [our issues](https://github.com/Cloud-CV/IDE/issues) on Github, the ones marked as `starter-project` are good places to start. Feel free to reach out to us on our [Gitter](http://gitter.im/Cloud-CV) channel if you have questions.

**Comment by helen-opetunde** [comment]
Hello @virajprabhu, I'd like to be part of this project for GSoC but I only know python and I am a data science student. Can I still be part of this project?

**Comment by virajprabhu** [comment]
Sure, @9jadataninja, and thanks for your interest. We use full-stack web technologies pretty extensively, so having some background in web would be helpful. If you're interested, I'd suggest you try setting up the project and browsing through our issue threads for something you might like to work on. Do ping us on Gitter if you have questions.

**Comment by aradhyamathur** [comment]
Hello @virajprabhu I would also like to be the part of this project for GSoC. I know python and Django and currently working towards learning ML. Can I also contribute to this project ?

**Comment by virajprabhu** [comment]
@aradhyamathur Absolutely! Please look at the instructions above.

**Comment by withai** [comment]
Hello @virajprabhu, I'd like to contribute to this project. I am familiar with Python, Tensorflow. Am I eligible to be part of this project?

**Comment by deshraj** [comment]
Hi @withai, glad that you are interested in this project. I think you have sufficient skillset for this project. Please go ahead and start with some of the getting started issues on the issues page of this project. Let us know if you need some help.

**Comment by SahibSethi** [comment]
Hey @deshraj , I would like to contribute to this project, I have sufficient experience with Python Django Development, and I am really keen on getting started with ReactJS and Deep Learning. I'm starting with the project setup and request to seek help from mentors if required.
Thanks.

**Comment by virajprabhu** [comment]
@withai @SahibSethi Absolutely! Please look at instructions above, and ping us on Gitter if you need any help setting up.

**Comment by sh92** [comment]
Hi, I would like to participate in gsoc project. So, I tried and succeed to install IDE. I have experience about django, tensorflow and Keras. And I am familiar with nodeJs. So, Can I participate in this project?

**Comment by Trion129** [comment]
Hy @virajprabhu, I am very interested in Cloud CV for GSoC, I have experience of web development and ReactJS. I have worked with Tensorflow and Keras on some of my projects. I am interested in Fabrik because it is a great service that will make Deep Learning more accessible and working on it will be a great learning experience! :smile:

**Comment by amsonu** [comment]
Hello @deshraj  I am interested in being a part of this project.I know python and I basically work on data  analysis,data mining and machine learning.I am a newbie in GSOC and I seek help from the mentors.
Thanks.

**Comment by evjak** [comment]
Hello. I can write a unit-tests if it possible

**Comment by umarbrowser** [comment]
Hello  @virajprabhu  I found this topic interesting and i want to apply for it

**Comment by deshraj** [comment]
Hi @umarbrowser, feel free to look for issues of this project on the issues page. Let us know if you  have doubts.

**Comment by umarbrowser** [comment]
ok thanks i looks forward to it

**Comment by BoseSean** [comment]
Hi @virajprabhu ,
Could I join this project as part of GSoc?
I just started learning ML and I am a CS student.

**Comment by ghost** [comment]
Hi @virajprabhu  

Could I join this project as a part of Gsoc?
I am currently working with Convolutional Neural networks. I find this very interesting and a great area to work on !

**Comment by manojbharadhwaj** [comment]
Hi @virajprabhu 
Could I join this project as part of GSoc?

**Comment by prasadwajekar** [comment]
Hi..
I am interested in this project...
