### ISSUE TITLE
Port EvalAI from Angular 1 to Angular 5

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/GSoC-Ideas#16]
**Project Title:** Port EvalAI from Angular 1 to Angular 5

**Description:** The current frontend code of EvalAI uses Angular 1. We want to migrate it to Angular 5 since it brings a lot of new features which brings easy maintainability, better SEO etc. Some of the initial tasks include:

- Getting started with Angular 5
- Setting up EvalAI-ngx (https://github.com/Cloud-CV/EvalAI-ngx)
- Setup Docker for EvalAI-ngx
- Setup CI/CD pipeline using Travis CI
- Implement the features in Angular 5 that are already present in current version
- Implement responsive web application
- Write the robust test suite
- Properly document the codebase
- Setup sphinx documentation
- Extended goals:
    1. Create a unique link for each of the entry on the leaderboard so that participant can share their entry position on the leaderboard
        - Make sure that meta tag for each entry link is different and shows participant team name, rank, score etc on the thumbnail when shared on some social media such as Twitter, Facebook, etc.
    2. Create a badge system for each of the entries on the leaderboard

- Integrate server side rendering for Angular 5

Besides this, students should also provide ideas of their own.

**Deliverables:**  The issues mentioned above should be implemented by the end of the GSoC period. Moreover, we expect students to also have implemented improvements that they have proposed.

**Mentors:** [Akash Jain](http://www.jainakash.in/) **@aka-jain**, [Shiv Baran Singh](http://www.shivbaran.in/) **@spyshiv**, [Rishabh Jain](https://rishabhjain2018.github.io/) 
                   **@rishabhjain2018**

**Co-Mentor(s):**[ Deshraj Yadav](https://deshraj.github.io/) **@deshraj**

**Skills:** AngularJS, Python, Django, Django rest framework

**Skill Level:** Medium

**Get started:** Take a look at our issues on Github. 

**Recommended:** Try to fix some issues (note that there are some issues labeled with **GSOC** on the project repository). For example, look at this issue: https://github.com/Cloud-CV/EvalAI-ngx/issues/46

**Important Links:** 

- EvalAI Website: https://evalai.cloudcv.org
- EvalAI Github repository: https://github.com/Cloud-CV/EvalAI
- EvalAI Docs: http://evalai.readthedocs.io/en/latest/
- Gitter Channel (for project related discussion): https://gitter.im/Cloud-CV/EvalAI
- GSoC Proposal Template: https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2018-Proposal-Template
- Mailing list: https://groups.google.com/forum/#!forum/cloudcv

**Comment by muddlebee** [comment]
Hey @RishabhJain2018 @aka-jain @spyshiv 
> Implement the features in Angular 5 that are already present in current version

What are the things one should mention for this? 

 ---
- What are you expecting out of a proposal? 
- How accurate should it be, like how much information should be there for the ideas above?

Can you please elaborate.

**Comment by deshraj** [comment]
@anweshknayak: Thanks for your interest in this project.

> What are you expecting out of a proposal?

We expect the following things from the student:
- Contributions in EvalAI-ngx repository (the todo list is out in the issue description) -- (**Remember: More the number of significant contributions, the more chances you have for selection**)
    - I would recommend to contribute in these areas in this project:
        - Help mentors in setting up the project (since the project is new)
        - Implement some features before GSoC Period ends (do mention the Pull Request Ids in the proposal)
        - Setup CI/CD pipeline for the project
        - Write robust test suite (shows that you know TDD)
        - Write exhaustive documentation (shows that you really care about the maintainability of the software)

- A detailed proposal describing:
    - What are the advantages and disadvantages of porting? (we want to test how good you are at exploring frameworks)
    - Suggest some extra features (discuss with mentors beforehand to make sure that it is a good feature to have)
    - A detailed weekly timeline how are you planning to work for the project
    - What are you planning to do in community bonding period? (detailed description)
    - What else are you planning to do in the summer? 
    - You can other details in the project proposal template: https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2018-Proposal-Template

> How accurate should it be, like how much information should be there for the ideas above?

We would like the proposal to be detailed but make sure that you don't fill the proposal with a lot of code. Think through and come up with new ideas, mention the ways of implementation, describe them using a neat flow chart, make contributions, mention the pull request link in the proposal (you can have a whole new heading for Pull Requests if you have done enough contributions :) )

I hope this clarifies your question. Please let us know if you still have concerns.

**Comment by yashLadha** [comment]
Are you planning of using Django as backend server for providing REST API to the main frontend UI that is going to be supported by Angular 5. @deshraj

**Comment by deshraj** [comment]
@yashLadha: that's correct.

**Comment by yashLadha** [comment]
@deshraj  Is there any repository for the Django Server also like as there for Angular Frontend?

**Comment by yashLadha** [comment]
Also @deshraj As I can see The Angular repository has no issues opened and it seems a fresh repo? So how to get started with the contribution? [Link](https://github.com/Cloud-CV/EvalAI-ngx)

**Comment by deshraj** [comment]
Here is the repository that contains the REST APIs: https://github.com/Cloud-CV/EvalAI

Also, we will start adding issues to the repository in next 36 hours. Till then, I think you should explore the current https://evalai.cloudcv.org and see how would you implement the existing features in Angular 5.

**Comment by yashLadha** [comment]
Thanks @deshraj Surely will try to contribute to the community. Thanks :smile:

**Comment by dhruvdutt** [comment]
Why aren't we porting it to React? We have Fabrik, Origami already on React. I think it would better for us to switch between multiple projects if all have similar technologies.

**Comment by deshraj** [comment]
@dhruvdutt: Good question. :) 

We intentionally wanted to port this project to Angular 5 instead of ReactJS because of the following reasons:

1. We wanted to try a new framework for one of our project (in this case it is EvalAI)
2. The project maintainers are very much comfortable with Angular 5 which makes it easier to maintain the project and saves a lot of time for our organization.
3. It happened to be the case that the project maintainers of other projects are comfortable in ReactJS and hence we started with React for those projects. 

I understand that you are comfortable with React but learning something new is always challenging and a involves lot of fun. We are looking for a student who can learn new technologies quickly even if he hasn't tried that (but as you know that most of the things are similar -- I am talking about the business logic). So, framework is not something that should be a problem here. :) 

I hope that answers your question.

**Comment by advait-net** [comment]
I would love to work as Google summer of code

**Comment by dhruvdutt** [comment]
@deshraj Can you please give an update on the state of the migration process?

**Comment by pavanrkadave** [comment]
I would love to contribute if the issue is still open

**Comment by RishabhJain2018** [comment]
Hi @pavanrkadave yeah, it is still open. We have built a version V1 for it and we will be adding more features to it in this summer. Here is the repository link: https://github.com/Cloud-CV/EvalAI-ngx. Please feel free to pick up any issue you would like to work on.

**Comment by pavanrkadave** [comment]
Hi @RishabhJain2018 Thanks for the info. i would love to contribute to it.

**Comment by RishabhJain2018** [comment]
Closing this issue since GSOC 2018 is over.
