### ISSUE TITLE
 Improve demo creation in Origami

### ISSUE THREAD

**Issue by AvaisP** [Cloud-CV/GSoC-Ideas#17]
**Project Title:** Improve demo creation in Origami

**Description:** 

Origami (previously called CloudCV-fy your code) is a AI-as-a-service solution that allows researchers to easily convert their deep learning models into an online service that is widely accessible to everyone without the need to setup the infrastructure, resolve the dependencies, and build a web service around the deep learning model. 

**Deliverable:**  

1. Drag and Drop demo creation (#78) 
2. Demo creation using markdown
3. Add support for dialogue like interface (#79)
4. Provide REST API to access models . 
5. Identify and fix all the UI bugs.
6. Configure auto deployment and deploy Origami
7. Writing robust unit tests for Origami-lib and Origami repository
8. Analytics page for your demos (Origami Insights)

**Mentor:** Avais Pagarkar @AvaisP, Utkarsh Gupta @uttu357 

**Skills:** 

- *Essential:* React JS, Python, Django, Flask Unix.
- *Preferred:* Docker, AWS

**Skill Level:** Medium

**Get started:** Take a look at our [issues](https://github.com/Cloud-CV/Origami/issues) on Github, the ones marked as `starter-project` are good places to start. Feel free to reach out to us on our [Gitter](https://github.com/Cloud-CV/Origami) channel if you have questions.

**Important links:**

- Origami Github: [https://github.com/Cloud-CV/Origami](https://github.com/Cloud-CV/Origami)
- Origami Docs: [http://cloudcv-origami.readthedocs.io/en/latest/](http://cloudcv-origami.readthedocs.io/en/latest/)
- GSoC Proposal Template: [https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2018-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2018-Proposal-Template)
- Gitter Channel: [https://gitter.im/Cloud-CV/Origami](https://gitter.im/Cloud-CV/Origami)
- Mailing list: [https://groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by jean72human** [comment]
Hi @AvaisP and @uttu357 . I am Gbètondji Dovonon. 
I am a second year student in Ashesi University college in Ghana. I really find this project interesting and would like to contribute as part of the GsoC 2018. It is my first time participating in a GSoC. 
I have a year of experience working either as a frontend developer (with react) or full stack (react + django + rest framework). I have never used AWS but rather DigitalOcean. I am also a machine learning enthusiast and I have explored librairies such as Keras, Tensorflow and Scikit Learn. 
I would like to contribute to Origami. How can I get started? 
Thanks.

**Comment by gupta-utkarsh** [comment]
@jean72human Check out the current issues open in Origami and you can start by fixing them and understanding how the application works. Try to host a demo on your local instance of Origami to get started.

**Comment by rokysungkar** [comment]
Hi, @AvaisP @uttu357 
I've planned to join GSoC 2018 and I'm very interested in this idea. I've read the proposal idea and decided that I want to join your idea. I know python and a little about Django, Docker, and AWS. I would love to the opportunity to discuss this idea with you and if you have advice for me for this idea I would appreciate it.

Best regards,
William Sungkar

**Comment by RadZaeem** [comment]
How many students can be accepted for CloudCV Origami? More than 1?

**Comment by deshraj** [comment]
@RadZaeem:  It depends on the quality of the student applications. If we find more than 1 deserving candidates, we won't hesitate to select multiple students.

**Comment by ashwinkjoseph** [comment]
Hi, I am Joseph Ashwin from Kerala. Currently a Full stack Developer with experience in Django, Laravel, Express.js, TypeScript, ReactJS, Flask, CodeIgniter. 
I would like to participate in the GSoC 2018 and contribute to this project.
However, I am new to GSoC and I am a bit confused.  I have looked into the template given. 
Do I choose an open issue of this project and submit my proposal based on that or do I submit a proposal on the implementation of any of the deliverables mentioned above?

**Comment by ashwinkjoseph** [comment]
Hi @AvaisP @uttu357 @deshraj , I am Joseph Ashwin from Kerala. Currently a Full stack Developer with experience in Django, Laravel, Express.js, TypeScript, ReactJS, Flask, CodeIgniter.
I would like to participate in the GSoC 2018 and contribute to this project.
However, I am new to GSoC and I am a bit confused. I have looked into the template given.
Do I choose an open issue of this project and submit my proposal based on that or do I submit a proposal on the implementation of any of the deliverables mentioned above?

**Comment by RishabhJain2018** [comment]
Closing this issue since GSOC 2018 is over.
