### ISSUE TITLE
Issues for GSOC 209

### ISSUE THREAD

**Issue by wadleo** [Cloud-CV/GSoC-Ideas#19]
**Project Title: Issues for GSOC 2019** 

**Description:** We need new issues for GSOC 2019, so potential students (like me) can know what projects to focus on and which issues to tackle for GSOC application.

**Deliverable:** List of issues

**Comment by RishabhJain2018** [comment]
Hi @wadleo , Thanks for your interest in the organization. We'll soon be releasing the ideas list. The issues for GSOC 2019 are already opened. You can search by tag `GSOC-2019` in EvaAI project. Also, do join our Gitter channel if you have any doubts/questions while setting up the project. Below are the links for it.
CloudCV: https://gitter.im/Cloud-CV/Lobby
EvalAI: https://gitter.im/Cloud-CV/EvalAI

**Comment by wadleo** [comment]
Thanks @RishabhJain2018 your reply very much appreciated.
