### ISSUE TITLE
Implementing RESTful web services for EvalAI

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/GSoC-Ideas#2]
**Project Title**: Implementing RESTful web services for EvalAI

**Description**: is an evaluation server that will host AI challenges like Visual Question Answering, Image Captioning. Our next goal of this project is to implement REST APIs. Some of the initial tasks include:

- ~~Add setInterval to API calls to get real-time data (see https://github.com/Cloud-CV/EvalAI/issues/653)~~ (Already fixed)
- Setup Continuous Deployment for EvalAI.
- Add integration tests using Selenium
- ~~Enforce unique random file name for files being uploaded~~ (Already fixed)
- ~~Create notification system for EvalAI~~ (Already fixed)
- Add number of concurrent request metric in metrics middleware
- Build a newsfeed for EvalAI (see https://github.com/Cloud-CV/EvalAI/issues/664)
- Build a dashboard for participants and hosts where they can analyze the submissions for a competition and get relevant insights
- Export the leaderboard table to Latex / PNG
- Webhooks for integrating it with other services / sites / chat-bots etc
- Scale the worker nodes system to run multiple competitions in the most optimal manner.
- Create an EvalAI badging system for the challenge evaluation script, challenge submissions, and top 10 leaderboard entries. For reference, see this https://github.com/badges/shields

Besides this, students should also provide ideas of their own.

**Deliverable**: the issues mentioned above should be implemented by the end of the GSoC period. Moreover, we expect students to also have implemented improvements that they have proposed.

**Mentor**: Taranjeet Singh @TroJan, Akash Jain @aka-jain, Shiv Baran Singh @spyshiv 

**Co-Mentor**:  Deshraj Yadav @deshraj

**Skills**: AngularJS, Python, Django

**Skill Level**: Medium

**Get started**: Take a look at our issues on Github. Try to fix some (note that there are some issues labeled with GSOC).

**Comment by muddlebee** [comment]
Currently EvalAi uses ES5. Would it be any good including the idea of migrating from ES5 to ES6 ?

**Comment by aka-jain** [comment]
@anweshknayak thanks for your suggestion, but shifting whole app from ES5 to ES6 will take huge time, basically then we have to revamp the whole site. Means, then we should have to go with Angular2 or React. And at this point when our app is almost in stable condition it will not be a good option to migrate to ES6. And we had this in our list from very begning. Will let everyone know once we decided in case of migrating.
Thanks :)

**Comment by AnshulBasia** [comment]
@deshraj Can you please elaborate the point Export Table to Latex / PNG ??

**Comment by Ragib95** [comment]
Hey,I am Dilnawaz Ragib pre-final year UG student at IIT Kharagpur. I want to be part of this project for GSoC. I have previous experience with Python and Django. What I need to do before submitting a proposal?

**Comment by deshraj** [comment]
Hi @Ragib95 please see our GSOC website http://gsoc.cloudcv.org. There is a patch requirement for each project that you need to satisfy. Please see https://github.com/Cloud-CV/GSoC-Ideas/wiki/Patch-Requirement for more details.

**Comment by evjak** [comment]
Hello! Can I work on CI/CD part?

**Comment by amittbhardwj** [comment]
Greetings, Right now I am occupied with my school examinations.
But, I plan to contribute to the CloudCV after April 2.
Is it okay to fulfil minimum patch requirement in the
week starting April 3?

**Comment by deshraj** [comment]
HI @amittbhardwj, the patch requirement is not mandatory. It is just to make sure that you have a good sense of the projects going on. It would be great if you can submit patch ASAP after 3rd April.

**Comment by guyandtheworld** [comment]
@deshraj Are the issues that are not striked off still available for taking?

**Comment by RishabhJain2018** [comment]
@isht3 Please take a look [here](https://github.com/Cloud-CV/EvalAI/issues) . You can take up any unassigned issue. :)
