### ISSUE TITLE
Monitoring setup for EvalAI admins

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/GSoC-Ideas#35]
**Project Title:** Monitoring setup for EvalAI admins

**Description:** 

As the number of challenges on EvalAI are increasing, we want to focus on improving the performance of our services. As a first step, we will focus on monitoring and measuring all the key metrics of our services. Insights from these will allow us to efficiently utilize our infrastructure, improve uptime and reduce costs. The project will concentrate on setting up metric reporting and alerts infrastructure, writing REST API’s, plotting relevant graphs and building analytics dashboards to help EvalAI admins maintain and monitor the services. 

**Deliverable:** 

- [x] Setup dockerized Grafana and Prometheus for reporting metrics
- [x] Add django-prometheus app package to EvalAI backend setup
- [x] Add prometheus counters to report metrics from EvalAI APIs to get metrics like number of HTTP 4xx, 5xx, 2xx
- [ ] Add model Mixin to report creation/deletion/update query rate for all the models
- [x] #45
- [ ] Create dashboards and plot graphs for all reported metrics on grafana. Each EvalAI app will have a separate dashboard.
- [ ] Setup cloudwatch metrics for system health like CPU, memory and storage utilization
- [ ] Add prometheus counters to report metrics from evaluation workers to get metrics like number of submissions in queue, number of submissions being processed, failed, etc. These metrics will give us an idea for how long workers are not processing submissions.
- [ ] Configure alerts for the metrics reported by EvalAI APIs, evaluation worker and system health to notify admins about critical issues like
- [ ] Worker not processing submissions
- [ ] Worker processing submission and marking all submissions as failed
- [ ] No qps on EvalAI backend i.e. server is down or not processing requests
- [ ] Number of exceptions thrown by APIs exceeds threshold
- [ ] Write tests for the monitoring APIs

**Mentor:** Deshraj Yadav (@deshraj), Rishabh Jain (@RishabhJain2018), Ram Ramrakhya (@Ram81)

**Skills:** Python, Django, Django rest framework, Docker

**Skill Level:** Medium

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2021)

**Important Links:**

- EvalAI Website: [eval.ai](https://eval.ai/)
- EvalAI Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI)
- EvalAI-ngx Github repository: [Cloud-CV/EvalAI-ngx](https://github.com/Cloud-CV/EvalAI-ngx)
- EvalAI Docs: [http://evalai.readthedocs.io/en/latest](http://evalai.readthedocs.io/en/latest)
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by afif-fahim** [comment]
@deshraj, @RishabhJain2018, @Ram81 Hi mentors. This idea seems very interesting to me. I would love to contribute to this issue!

**Comment by RishabhJain2018** [comment]
Hey @afif-fahim, Welcome to CloudCV!

Please get started by picking up issues in the EvalAI repository.

**Comment by afif-fahim** [comment]
@RishabhJain2018, Can I start working on the issues mentioned in this project idea?

**Comment by aitalshashank2** [comment]
Hello @RishabhJain2018, @Ram81, @deshraj! I have been working with Django, Django Rest Framework and Docker for about an year now and I have been exploring Kubernetes for a month. I have set the project up as well. I look forward to contribute to this project whilst increasing my knowledge base at the same time. Can I take one of the issues mentioned above?

**Comment by palrohitg** [comment]
Hi, @Ram81 @RishabhJain2018  @deshraj firstly congrats to you guys, you are so active here and working on a great product. 
I am Vikas Pal, currently in my prefinal year (CSE) more interested in the backend stuff and scaling application, active open-source developer. 
Since I am more curious to know what happens to a product that has large user-based like Facebook, Amazon, etc? How they able to process millions of requests without much latency/delay ? How the backend / DevOps team monitoring the resource and scaling the resource based on user, cost, etc. 
This curiosity leads to learning more about the backend, API, DevOps, etc. How does the microservices architecture follow in a company, resource scaling all that stuff? 
That the big reason I am here, a Monitoring system for EvalAI completely aligns with the interest and curiosity too.  
I found the outcome of the projects is really massive because no one want when submitting their evaluation, requesting to the server that should be quick/fast, the customer had a great experience while using the applications. 

I already set up the local-dev, it working great, and thanks for providing the containerize installation setup. It really saved a lot of time. I am just going through the codebase for a couple of days now.  Started working on design architecture part Monitoring,  contiuous scaling and  alerting. 

Hope u all guys, guide me, provide the continuous feed-back during the whole journey. 

Skiilset : 
language : c++, python 
Framwork : Django, Flask 
Database : postgres, mongodb 
DevOps : Docker, AWS

**Comment by bernandez** [comment]
I am interested in this project especially the part where a dashboard is created

**Comment by ravindranath-sawane** [comment]
Hello, @Ram81 @RishabhJain2018 @deshraj I'm a Student Pursuing B.Tech. in Artificial Intelligence I'm really interested to learn about this type of project.

**Comment by hvsblogger** [comment]
Hi, @Ram81 @RishabhJain2018 @deshraj I am a Mtech student from IIIT and am willing to work on this project. I did an internship in Cloud Ops and Automation in webscoot e-commerce company also I did 4 RedHat certification Redhat certified in system administration, Redhat certified engineer, Red Hat Certified Specialist in Virtualization, Red Hat Certified Specialist in Ansible Automation, and DevOps administration from LinkedIn learning. I am also attaching the screenshot of ( 1 .  Setup dockerized Grafana and Prometheus for reporting metrics ) here and used docker as said, It would be a great opportunity to work with you on this GSCO project and upgrade my skill. Looking forward to work
![Screenshot from 2021-04-05 12-00-43](https://user-images.githubusercontent.com/37100463/113547651-f7bb8380-960b-11eb-8bf0-90a73e77b2c9.png)
![Screenshot from 2021-04-05 11-57-43](https://user-images.githubusercontent.com/37100463/113547658-fa1ddd80-960b-11eb-8a3b-7a1d0bd74857.png)
![Screenshot from 2021-04-05 11-56-54](https://user-images.githubusercontent.com/37100463/113547662-fb4f0a80-960b-11eb-8626-b35ab9cc822e.png)
![Screenshot from 2021-04-05 11-53-35](https://user-images.githubusercontent.com/37100463/113547675-fe49fb00-960b-11eb-964f-7d41c459426b.png)
![Screenshot from 2021-04-05 11-52-01](https://user-images.githubusercontent.com/37100463/113547685-00ac5500-960c-11eb-994a-24aa36f404f9.png)





![Screenshot from 2021-04-05 12-01-31](https://user-images.githubusercontent.com/37100463/113547641-f5592980-960b-11eb-823d-c6b643bed963.png)

**Comment by TheNobody-12** [comment]
hi @Ram81 @RishabhJain2018   i am sarthak kapaliya i love this project idea.
i am B.tech  computer science first year  student. i am very much excited to join these project on GSOC 2021.
i know programming languages like python and C. This is my first open source  project . 
i have less knowledge of django and dockers. please help me in this . 
Can you tell me some new things which should learn so i can contribute in this project ?.
i will dedicate with full energy in this project to learn new things please help me 
thank you

**Comment by sa-y-an** [comment]
@Ram81 @RishabhJain2018 @deshraj 
Will EVAL AI participate in GSoC 2022 with this project? 
I want to work on this project.

**Comment by mr-vaibh** [comment]
@Ram81 I'm up for it!!
