### ISSUE TITLE
Analytics dashboards for challenge hosts and participants

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/GSoC-Ideas#37]
**Project Title:** Analytics dashboards for challenge hosts and participants

**Description:** 

This project will involve writing REST API’s, plotting relevant graphs and building analytics dashboards for challenge hosts and participants. The analytics will help challenge hosts view the progress of participants in their challenge -- for instance, comparing the trends of the accuracy from participant submissions over the period of time. Participants will be able to visualize the performance of all of their submissions with time and their corresponding rank on the leaderboard. The final goal is to provide users with several analytics to track their progress on the platform.

**Deliverable:** 

1. For challenge host -

    - [ ] Add APIs to fetch and aggregate metrics for the performance of a participant in a challenge over a period of time.
    - [ ] Add frontend changes to plot graphs for the metrics fetched from the APIs.
    - [ ] Add backend APIs and plot for showing the number of submissions in a challenge by a participant.
    - [ ] Add backend APIs and plots for showing the number of submissions in a challenge in a day, month, and yearly.
    - [ ] Add backend APIs and plot to show the ranks of various participants on the leaderboard over time.
    - [ ] Add backend APIs and plot for the evaluation time of submissions over time.
    - [ ] Write tests for the APIs and frontend

2. For participants -

    - [ ] Add backend APIs and graphs for checking the trend of submissions in a challenge and the corresponding rank.
    - [ ]   Add backend APIs and plot for the number of submissions in a challenge over time which can be filtered by submission status.
    - [ ]   Write tests for the APIs and frontend

**Mentor:** Rishabh Jain (@RishabhJain2018), Ram Ramrakhya (@Ram81)

**Skills:** Angular 7, Django, Django Rest Framework, D3.js

**Skill Level:** Medium

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2020)

**Important Links:**

- EvalAI Website: [eval.ai](https://eval.ai/)
- EvalAI Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI)
- EvalAI-ngx Github repository: [Cloud-CV/EvalAI-ngx](https://github.com/Cloud-CV/EvalAI-ngx)
- EvalAI Docs: [http://evalai.readthedocs.io/en/latest](http://evalai.readthedocs.io/en/latest)
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by anukritigupta24** [comment]
Hi,
I am interested in working on this project. I have good experience in writing APIs and building dashboards. I have already worked with Angular, Flask, REST APIs, Vue.js, React.js, HTML, CSS, JavaScript, Node.js, etc. As an intern I have worked on similar technologies and same type of work, so I have good experience with this. It would be great to work on this. Please let me know about how can I start working on this.

**Comment by mayank444** [comment]
Venerated Sir,
I hope you are safe and in good health in the wake of prevailing COVID-19.
My name is Mayank Parashar and I am a 3rd-year Computer Science undergraduate student at JCBOSE YMCA University. I have been working with Python, machine learning, and deep learning for a couple of years now and have in-depth knowledge of it. I look forward to contributing to this idea as part of this year's GSoC.
It would be a great assistance if you could suggest how to get started.

**Comment by RishabhJain2018** [comment]
Hi @anukritigupta24 and @mayank444, Welcome to CloudCV!

Thank you for your interest in the project. As a starting point, you both should first setup EvalAI development environment on your local machine or at the place where you do development. After that, you should look for starter issues in the EvalAI GitHub repository. You should solve a bunch of issues to get familiar with the project codebase.

Moreover, please take a look at our GSoC proposal template here -- https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template. You will have to submit a proposal to Google in order to participate in the program. I recommend that you should start early with the proposal so that we can review it before the deadline. Also, we expect a detailed proposal from students.

Please feel free to ask if you have any questions/doubts.

**Comment by suryaremanan** [comment]
Hi @RishabhJain2018 ,

I am a second-year BCA student who has experience interning at a startup as a Data Scientist. I have deep knowledge of machine learning and have worked on various projects. 
I am interested and look forward to contributing to this idea. 

Kind Regards
Kumari Surya Remanan

**Comment by suryaremanan** [comment]
@RishabhJain2018 , I just finished setting up the EvalAI development environment on my pc

**Comment by suryaremanan** [comment]
@Ram81, @RishabhJain2018 I get the below screen on trying to join the mailing list. What should I do?
![Screenshot](https://user-images.githubusercontent.com/17148269/112324595-fbc8d680-8cd8-11eb-994e-aa0348f913a4.png)

**Comment by RishabhJain2018** [comment]
Hi @suryaremanan, It is fixed and should work now!

**Comment by vasukivenkatesh** [comment]
Hi @RishabhJain2018 I am Vasuki Venkatesh, a first year masters student in Computer Science at The University of Texas at Dallas. I would love to work on this project and contritbute.

**Comment by huskhi** [comment]
Hi all!
I'm a beginner in contribution to open source but I'm highly interested and motivated to work on this project. Please let me know how can I start with working on this project?

**Comment by RUDRANSH-hub** [comment]
hii @RishabhJain2018 

my name is  Rudransh Srivastava currently doing btech with Information Technology branch in 2nd year of my btech. and i have knowledge of python, Machine learning and very much interested in to contribute in your respected organization. please guide me how may i initiate my work to serve your organization through GSoC

**Comment by VimukthiRandika1997** [comment]
Hey!,
I am interested in working on this project. I have sound knowledge in writing APIs and building web apps. I have already worked with Angular, Flask, REST APIs, React.js, HTML, CSS, JavaScript, Node.js, etc. Please let me know about how can I begin working on this.
