### ISSUE TITLE
Improvements in EvalAI frontend

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/GSoC-Ideas#38]
**Project Title:** Improvements in EvalAI frontend

**Description:** 

After last year’s GSOC, we’ve reached feature parity on EvalAI-ngx with the existing UI, this project will involve fixing the last remaining kinks in the UI. The goal of this project would be to improve the new UI as we replace the existing UI with the new UI before GSOC. We will be improving on the new UI and incorporating the feedback we will receive from the challenge hosts and participants for the AI challenges organized this year. 

**Deliverable:**

- [x] Add testimonials, statistics on the home page
- [x] Add a feature to allow collapsing metrics on the leaderboard to make it easier to view details when the leaderboard has a lot of metrics.
- [ ] Add meta tags for each challenge page. If a user shares some challenge page link on twitter, then it should show the details of challenge and challenge cover picture instead of EvalAI image.
- [ ] Add challenge evaluation script, test annotations edit feature in settings tab
- [ ] Add frontend changes to upload the html field for overview page or allow editing html on the edit dialog of overview page.
- [ ] Add frontend changes to upload the html field for terms and conditions page or allow editing html on the edit dialog of overview page.
- [ ] Add changes to redirect user to challenge page once a user uploads a challenge
- [ ] Show cli commands to update test annotations on phases tab to challenge hosts.
- [ ] Show progress bar when a participant is uploading a submission from UI.
- [ ] Add search option on all challenges and hosted challenges page
- [ ] Show worker status (active, inactive, error) on challenge manage tab. It will make status checking easier for hosts instead of going through logs.
- [ ] Fix inconsistent padding and font weight across the UI.

**Mentor:** Kajol Kumari (@Kajol-Kumari), Mayank Lunayach (@lunayach), Rishabh Jain (@RishabhJain2018), Ram Ramrakhya (@Ram81)

**Skills:** Angular 7, HTML, CSS, Typescript

**Skill Level:**  Medium

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2021)
**Important Links:**

- EvalAI Website: [eval.ai](https://eval.ai/)
- EvalAI-ngx Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI-ngx)
- EvalAI Docs: [http://evalai.readthedocs.io/en/latest](http://evalai.readthedocs.io/en/latest)
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by Shivani-Goud** [comment]
@Ram81 I'm interested in working in these issues. Can I get a task assigned and  directions on getting started ? I can start off with "Show progress bar when a participant is uploading a submission from UI."  task .

**Comment by RishabhJain2018** [comment]
Hi @Shivani-Goud, Welcome to CloudCV!

Please feel free to pick any task that you like, open an issue for the same and we can assign that to you.

**Comment by Shivani-Goud** [comment]
@RishabhJain2018   I have opened this [issue ](https://github.com/Cloud-CV/GSoC-Ideas/issues/40) .

**Comment by Alabhya268** [comment]
@lunayach  @RishabhJain2018  @Ram81  Hi mentors, I've been contributing to EvalAI project for a while now and I am good with Angular and Django. I want to contribute to these issues.

Could you also please let me know how many slots Cloud-CV requests  for GSOC.
Thanks in advance.

**Comment by Alabhya268** [comment]
@RishabhJain2018  @Ram81 @lunayach  CloudCV mailing list is not working , Could you please help me.
It shows ```Content unavailable```.

**Comment by nhannqgh** [comment]
Hi @Ram81,
I am interested in solving this issue "Add meta tags for each challenge page. If a user shares some challenge page link on twitter, then it should show the details of challenge and challenge cover picture instead of EvalAI image". I created [this issue](https://github.com/Cloud-CV/GSoC-Ideas/issues/41). Can I start now?

**Comment by mayank444** [comment]
Venerated Sir,
I hope you are safe and in good health in the wake of prevailing COVID-19.
My name is Mayank Parashar and I am a 3rd-year Computer Science undergraduate student at JCBOSE YMCA University. I have been working with Python, Swift, and deep learning for a couple of years now and have in-depth knowledge of it. I look forward to contributing to this idea as part of this year's GSoC.
It would be a great assistance if you could suggest how to get started.

**Comment by RishabhJain2018** [comment]
Hi @Alabhya268 ,

Thank you for the contributions and we look forward to your proposal 🎉 

>Could you also please let me know how many slots Cloud-CV requests for GSOC.

Sorry, we are not authorized to give out this information but I can tell you that we will have sufficient slots for every project.

>CloudCV mailing list is not working , Could you please help me.
It shows Content unavailable.

Can you please post the screenshot and the link you are trying to access?

**Comment by RishabhJain2018** [comment]
> Hi @Ram81,
> I am interested in solving this issue "Add meta tags for each challenge page. If a user shares some challenge page link on twitter, then it should show the details of challenge and challenge cover picture instead of EvalAI image". I created this issue. Can I start now?

Hi @nhaancs, Welcome to CloudCV!

Sorry, this issue is already taken. Please feel free to pick up any other issue.

**Comment by RishabhJain2018** [comment]
> Venerated Sir,
> I hope you are safe and in good health in the wake of prevailing COVID-19.
> My name is Mayank Parashar and I am a 3rd-year Computer Science undergraduate student at JCBOSE YMCA University. I have been working with Python, Swift, and deep learning for a couple of years now and have in-depth knowledge of it. I look forward to contributing to this idea as part of this year's GSoC.
> It would be a great assistance if you could suggest how to get started.

Hi @mayank444, Welcome to CloudCV!
 
Thank you for your interest in the project. As a starting point, you both should first setup EvalAI development environment on your local machine or at the place where you do development. After that, you should look for starter issues in the EvalAI GitHub repository. You should solve a bunch of issues to get familiar with the project codebase.

Moreover, please take a look at our GSoC proposal template here -- https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template. You will have to submit a proposal to Google in order to participate in the program. I recommend that you should start early with the proposal so that we can review it before the deadline. Also, we expect a detailed proposal from students.

Please feel free to ask if you have any questions/doubts.

**Comment by Alabhya268** [comment]
@RishabhJain2018 , I am getting this type of error.
![Capture](https://user-images.githubusercontent.com/57143358/111034246-86e8c900-83c9-11eb-87b7-9ff191219ba1.PNG)

**Comment by RishabhJain2018** [comment]
@Alabhya268 Can you please try this link -- https://groups.google.com/g/cloudcv

**Comment by Alabhya268** [comment]
> @Alabhya268 Can you please try this link -- https://groups.google.com/g/cloudcv

@RishabhJain2018, I'm  still facing same issue with this link.

**Comment by ankitpal1029** [comment]
Hey i'm Ankit,
I am interested in contributing to the project so far i have setup the docker dev env, @RishabhJain2018  can you please guide me as to  which issues i should attempt going from here.

**Comment by ankitpal1029** [comment]
@RishabhJain2018 @Ram81  can i work on https://github.com/Cloud-CV/EvalAI/issues/2618 this issue? i thought i could maybe use the ngx-cookieconsent library for this what are your views regarding this.

**Comment by MayankGeek** [comment]
Can I work on Fix inconsistent padding and font-weight across the UI ?

**Comment by vaibhavjack11** [comment]
I have worked On Angular 7 
I made a blog Posting Application I can Do this Work both front end and backend also with firebase

i want to do this task

**Comment by AaqibAhamed** [comment]
I would like to contribute on Cloud CV in any angular related available ideas.May I know what are the deliverable available ?

**Comment by AaqibAhamed** [comment]
@RishabhJain2018 @Ram81  I would like to working in these issues. Can I take "Add search option on all challenges and hosted challenges page" Task ?. 

Also I have created an issue #43 for this task .
Can I get some guidnce to get start?.
Also see my commits and PR

**Comment by aditya-5** [comment]
Hello
I am very new to Open Source Contributions. My bad that I discovered Google GSoC so late. I have a fair amount of experience with Python and Angular. How can I get started with an issue? 
I did a little research and I believe it's way to late to write a proposal now.
