### ISSUE TITLE
Show progress bar when a participant is uploading a submission from UI  - Improvements in EvalAI frontend 

### ISSUE THREAD

**Issue by Shivani-Goud** [Cloud-CV/GSoC-Ideas#40]
**Project Title:** Showing a progress bar while uploading a submission

**Description:** This is one of the expected task in the  process of improving the existing UI  before GSOC 2021. The expected tasks are from  the feedback received from the challenge hosts and participants for the AI challenges organised that year.

**Deliverable:** Show progress bar apt to the style and theme of the application  when a participant is uploading a submission from UI.

**Mentor:** @RishabhJain2018 

**Skill Level:**  Medium

**Comment by MRafaydev** [comment]
Hey @Shivani-Goud I want to contribute on this issue....

**Comment by suryaremanan** [comment]
hi @Shivani-Goud , I want to contribute to this issue

**Comment by trayansh** [comment]
Hey @Shivani-Goud am Also Interested To Contribute To this Issue.

**Comment by AaqibAhamed** [comment]
Is this still available ?

**Comment by Ram81** [comment]
We have opened a issue for this task on [EvalAI](https://github.com/Cloud-CV/EvalAI/issues/3702). Closing this.
