### ISSUE TITLE
Add meta tags for each challenge page. If a user shares some challenge page link on twitter, then it should show the details of challenge and challenge cover picture instead of EvalAI image.

### ISSUE THREAD

**Issue by nhannqgh** [Cloud-CV/GSoC-Ideas#41]
**Project Title:** Improvements in EvalAI frontend

**Description:** Add meta tags for each challenge page. If a user shares some challenge page link on twitter, then it should show the details of challenge and challenge cover picture instead of EvalAI image.

**Deliverable:**

**Mentor:** 

**Skills:**

**Skill Level:**

**Get started:**

**Comment by Ram81** [comment]
Closing this issue. Duplicate issue. Original issue is [here](https://github.com/Cloud-CV/EvalAI/issues/3297)
