### ISSUE TITLE
Add search option on all challenges and hosted challenges page

### ISSUE THREAD

**Issue by AaqibAhamed** [Cloud-CV/GSoC-Ideas#43]
**Project Title:** Add search option on all challenges page

**Description:** General information about the project, avoid one Liners, the description should be as detailed as possible.

**Deliverable:** Expectations from the student at the end of the project

**Mentor:** Who is the mentor? Who is the Co-Mentor? Also please assign the issue to the mentor!

**Skills:** Which skills are needed? Programming languages, frameworks, concepts etc.

**Skill Level:** Easy, Medium, Hard

**Get started:** Tasks that mentors may want to suggest students so that they can start contributing to the code base (e.g. junior jobs, low hanging fruits, discussion on the mailing list)

**Comment by Ram81** [comment]
We have opened a issue for this task on [EvalAI](https://github.com/Cloud-CV/EvalAI/issues/3701)
