### ISSUE TITLE
Query Regarding GSoC 2022

### ISSUE THREAD

**Issue by uzaxirr** [Cloud-CV/GSoC-Ideas#44]
Hey @RishabhJain2018 
I see #37 was a GSoC 2021 Idea but hasn't been implemented yet, are there any plans of Cloud-CV to participate in GSoC 2022 if yes then which all projects will be taking part in that??
EvalAI??

**Comment by ahmadateya** [comment]
I questioning about that too

**Comment by Ram81** [comment]
Hi @uzaxirr we have opened issues for the GSoC'22 Ideas. You can find them in #47 #46
