### ISSUE TITLE
Analytics dashboards for challenge hosts and participants

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/GSoC-Ideas#47]
**Project Title:** Analytics dashboards for challenge hosts and participants

**Description:** 

This project will involve writing REST API’s, plotting relevant graphs and building analytics dashboards for challenge hosts and participants. The analytics will help challenge hosts view the progress of participants in their challenge -- for instance, comparing the trends of the accuracy from participant submissions over the period of time. Participants will be able to visualize the performance of all of their submissions with time and their corresponding rank on the leaderboard. The final goal is to provide users with several analytics to track their progress on the platform.

**Deliverable:** 

1. For challenge host -

    - [ ] Add APIs to fetch and aggregate metrics for the performance of a participant in a challenge over a period of time.
    - [ ] Add frontend changes to plot graphs for the metrics fetched from the APIs.
    - [ ] Add backend APIs and plot for showing the number of submissions in a challenge by a participant.
    - [ ] Add backend APIs and plots for showing the number of submissions in a challenge in a day, month, and yearly.
    - [ ] Add backend APIs and plot to show the ranks of various participants on the leaderboard over time.
    - [ ] Add backend APIs and plot for the evaluation time of submissions over time.
    - [ ] Write tests for the APIs and frontend

2. For participants -

    - [ ] Add backend APIs and graphs for checking the trend of submissions in a challenge and the corresponding rank.
    - [ ]   Add backend APIs and plot for the number of submissions in a challenge over time which can be filtered by submission status.
    - [ ]   Write tests for the APIs and frontend

**Mentor:** Gautam Jajoo (@gautamjajoo), Rishabh Jain (@RishabhJain2018), Ram Ramrakhya (@Ram81)

**Skills:** Angular 7, Django, Django Rest Framework, D3.js

**Skill Level:** Medium

**Project size** - 175 hours

**Difficulty** - Medium

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2022)

**Important Links:**

- EvalAI Website: [eval.ai](https://eval.ai/)
- EvalAI Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI)
- EvalAI Docs: [http://evalai.readthedocs.io/en/latest](http://evalai.readthedocs.io/en/latest)
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by hesphoros** [comment]
please give me a opportunity
