### ISSUE TITLE
 Analytics Dashboards for EvalAI Users

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/GSoC-Ideas#58]
**Project Title:**  Analytics Dashboards for EvalAI Users

**Description:** The goal of this project is to provide challenge hosts and participants with insightful analytics to track their progress on the platform. This project will involve writing REST APIs, plotting relevant graphs, and building analytics dashboards for both challenge hosts and participants. The analytics will help challenge hosts view the progress of participants in their challenge (changes in performance and ranking over time), and participants will be able to visualize the performance of all their submissions over time and their corresponding rank on the leaderboard.

**Deliverable:** Expectations from the student at the end of the project
1. For Challenge Hosts:
    - [ ]  Implement APIs to fetch and aggregate metrics for participant performance in a challenge over a period of time.
    - [ ] Develop frontend changes to plot graphs for the metrics fetched from the APIs.
    - [ ] Implement backend APIs and plots for showing the number of submissions in a challenge by a participant, and the evaluation time of submissions over time.
    - [ ] Create backend APIs and plots to show the ranks of various participants on the leaderboard over time and the number of submissions in a challenge by day, month, and year.
    - [ ] Write tests for the APIs and frontend.
2. For Participants:
    - [ ] Implement backend APIs and graphs for checking the trend of submissions in a challenge and the corresponding rank.
    - [ ] Develop backend APIs and plots for the number of submissions in a challenge over time, filtered by submission status.
    - [ ] Write tests for the APIs and frontend.

**Mentor:** Gunjan Chhablani, Ram Ramrakhya

**Skills:** Angular 7, Django, Django Rest Framework, D3.js

**Skill Level:** Medium

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2023)

**Important Links**:

- EvalAI Website: [eval.ai](https://eval.ai/)
- EvalAI Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI)
- EvalAI Docs: http://evalai.readthedocs.io/en/latest
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by Bhaarat-khatri** [comment]
Hello @Ram81 , @gchhablani I went through the EvalAI website and get to know its work. From my understanding I get to know this tell help us compare the ml,ai algorithm models and tell which is better. This project interest me a most, I want to be the part of this project for this summer. It will be a kind of you, if you will provide a further detail, how to start contribution for this project. I have gone through its repo "cloudCV/evalAI" but unable to find any recent good first issue to quick start.

About my self,
I am a final undergraduate from INDIA. I am currently pursuing B.Tech through Information Technology.
About my professional life, I was the past participants of GSOC'21 program for an wikimedia org. where I worked on improving UI/UX of wikimedia portals. 

Please help me to get started.

**Comment by CodeDetector** [comment]
Hello @Ram81 and @gchhablani .I am a prefinal year CSE student and have experience in developing RestAPIs . I am currently interning as a data analyst and appreciate how you are trying to improve the challenge host as well as participant experience on the platform in this project . I am highly motivated to contribute to the project this summer , and would appreciate if you could point out a good first issue .

**Comment by purna135** [comment]
Hi Gunjan and Ram,

I am writing to express my interest in participating in the "**Analytics Dashboards for EvalAI Users**" project for GSoC 2023. As a participant in GSoC 2022, where I worked with PyMC and Aesara, I gained valuable experience in building machine learning models and contributing to open-source projects.

The proposed project is particularly appealing to me because it involves developing analytics dashboards for challenge hosts and participants using Angular 7, Django, Django Rest Framework, and D3.js. I have experience working with Angular and Django, and I am confident that I can quickly learn and master the other technologies involved in this project.

I am excited about the opportunity to work with you and contribute to the EvalAI project, which provides a valuable platform for researchers and developers to collaborate and evaluate machine learning models. I believe that this project will allow me to hone my skills in building scalable and robust web applications, while also making a meaningful contribution to the open-source community.

Thank you for your time. I look forward to hearing from you soon.

**Comment by purna135** [comment]
the Gitter link provided in the project description ([gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)) seems to be broken. When I tried to access it, I received an error message "404 Not Found". 

If you have an updated link, please let me know.

**Comment by pavan12395** [comment]
Hi Gunjan and Ram,

I want to participate in this Project "Analytics DashBoards for EvalAI Users" project GSOC 2023, I have experience building applications using Front end Applications using Angular and Web APIs using Django, I easily adapt to any new frameworks

I am an Undergraduate student currently working in a startup as Software Developer Intern, I look forward to this opportunity,I believe that this project will give me valuable experience and helps me in honing my skills.

I Look Forward to Hearing From You

**Comment by purna135** [comment]
Hi @gchhablani

I am writing to follow up on my previous message expressing my interest in participating in the "Analytics Dashboards for EvalAI Users" project for GSoC 2023.

I am very excited about the prospect of contributing to the EvalAI project and developing analytics dashboards using Angular 7, Django, Django Rest Framework, and D3.js. As mentioned earlier, I have experience working with Django, and I am eager to learn and master the other technologies required for this project.

I would appreciate any feedback you may have on my proposal and whether I have met your expectations in terms of the necessary qualifications and experience. Additionally, please let me know if there are any steps I can take to improve my chances of being selected for this project.

Thank you for your time.

**Comment by marinicadenisandrei** [comment]
Hi Gunjan and Ram,

I am very interested in participating for the "Analytics Dashboards for EvalAI Users" program offered by GSOC 2023.

I am very passionate about this field, I currently work for companies that use the same technologies and I am also a master's student with a profile focused on these technologies. I would like to interact with a very well developed team, from which I can learn a lot of things and to be able to interact and implement all the knowledge to contribute to this project.

I am very passionate, I want to devote myself a lot to the project and to be able to participate in this GSOC 2023 program.

**Comment by gchhablani** [comment]
@Bhaarat-khatri @purna135 @pavan12395 @marinicadenisandrei 

Thank you for reaching out to us regarding the Google Summer of Code (GSoC) 2023 program. We appreciate your interest in our project and we are excited to have you as a potential participant.

As you may have seen, we have some open issues that we are looking into for both EvalAI and EvalAI-CLI. You can find them on our Github page at the following links:

- On EvalAI: https://github.com/Cloud-CV/EvalAI/issues?q=is%3Aissue+is%3Aopen+label%3AGSoC-2023
- On EvalAI-CLI: https://github.com/Cloud-CV/evalai-cli/issues/342

We encourage you to experiment with EvalAI and report any issues that you come across. We will be posting more issues soon, so stay tuned for those.

We have a Slack workspace that you can join to connect with other interested participants. Here's the link to join: https://join.slack.com/t/cloudcv-community/shared_invite/zt-1rkm0m8pw-TBkjRjx~_GyIvMVlF5iDHg

Once you're in, you can join the #gsoc-23-interested-participants channel to stay up to date on the latest news and discuss the project with other potential participants.

In the meantime, we encourage you to set up EvalAI locally and continue revising your proposal before the final deadline. If you have any questions or concerns, don't hesitate to reach out to us.

Hi, and welcome to the CloudCV community!

Best regards,

Gunjan Chhablani

**Comment by snehalchaudhari98** [comment]
Hi Gunjan and Ram, 

I am Snehal Chaudhari, a computer science graduate student and I would like like to collaborate on this project. I am excited to express my interest in this project as it is a interesting task  where I could reapply my past experiences especially with D3. After going through the project description, I believe that this project has great potential to provide valuable insights to challenge hosts and participants on the platform. I believe that I can contribute significantly to this project with my skills and knowledge. 

I am eager to work on this project and contribute to the development of REST APIs, plot relevant graphs the areas where I have prior experience. I am committed to devoting my time and effort to the project to ensure its successful completion and learn from the community. Hope to connect with you guys on Slack as well.

Thank you !!

**Comment by priyanshmathur** [comment]
Hi,
My name is Priyansh Mathur, and I am in the Pre-final year of my Bachelor's degree in Computer Science and Engineering at PES University, Bengaluru, India.
I am very interested in participating in the “Adversarial Data using Gradio and EvalAI”


I would like to contribute to your Organization by taking part in the GSOC '23 and helping you build fault-tolerant, efficient and reliable products for your Organization using the skills I have and learning from the experts who are in this field for numerous years.


I'm excited about the opportunity to work on this project and utilize my experience to develop REST APIs and create relevant graphs. I'm fully dedicated to investing my time and effort to ensure the project's success and learn from the community. Looking forward to connecting with everyone on Slack.

You can reach out to me through my email id provided below:
[mathur.priyansh15@gmail.com](mailto:mathur.priyansh15@gmail.com)

**Comment by SJ-Kumar** [comment]
Dear Mentors,

My name is Jayanth Kumar, and I am currently pursuing an undergraduate degree in Computer Science. I am writing to express my interest in participating in the GSoC program this year. I am excited to express my interest in the "Analytics Dashboards for EvalAI Users" project for GSoC 2023. After going through the project description and requirements, I am convinced that this project aligns with my skills and interests.

I have prior experience working with REST APIs and plotting graphs, which I believe will be valuable for the project. Additionally, I have worked with Django, which has equipped me with the necessary skills to develop a scalable and robust web application. Furthermore, my experience working with Django has provided me with the knowledge and skills to develop web applications that are scalable, secure, and maintainable. I have worked on projects involving user authentication, database management, and server-side rendering, which has honed my skills in working with Django. In addition to my prior experience with REST APIs, I have also obtained the Postman Student Expert Certification. This certification demonstrates my proficiency in using Postman, a popular tool for testing and documenting APIs.  Having the Postman Student Expert Certification has allowed me to enhance my skills in API development and testing, which I believe will be useful in developing the analytics dashboards for EvalAI users. With this certification, I am confident in my ability to develop and test REST APIs that are reliable, secure, and scalable.

Overall, I believe that my prior experience makes me well-suited for this project. I am thrilled about the opportunity to contribute to CloudCV. I am confident that I will be able to hone my skills and make a meaningful contribution to the open-source community.

Regards,
Jayanth Kumar

**Comment by anant-vsr** [comment]
Hi Gunjan and Ram,

I am Anant Vikram Singh Rathore, a computer science undergraduate student and I would like to collaborate on this project. I am excited to express my interest in this project as it is a interesting task where I could reapply my past experiences. After going through the project description,  I believe that I can contribute significantly to this project with my skills and knowledge.

I am Looking forward to work on this project and contribute to the development of REST APIs, plot relevant graphs the areas where I have prior experience. I am committed to devoting my time and effort to the project to ensure its successful completion and learn from the community.

Thank you !!

**Comment by 19-ayushi** [comment]
Dear Mentors,
I am Ayushi, a third-year computer science student. I am skilled in C, C++, Python, HTML, CSS, JavaScript, and Django.
I am interested in working on the project. I believe my knowledge of Django will help to make useful contributions. I am also learning the D3 library, which I look forward to putting to practical use. 
I am looking forward to putting my knowledge and time into this project as well as gaining more experience through the whole process.
Thank you

Regards
Ayushi

**Comment by Pratikparvat** [comment]
Dear Mentors,

I am Pratik Parvat, Third-year Computer Engineering student from Nashik.  I would like to join on this project. I am excited to express my interest in this project as it is my goal to learn dashboard designing and to know more about its features and building process. . I am skilled in Java, C++, Python, HTML, CSS, JavaScript, Django framework and also know about basics of Data science .
I am Looking forward to work on this project and contribute to the development of project. I am devoting my time and effort to the project to ensure its successful completion and successful learning.
Thanking you in anticipation.

Regards,
Pratik Parvat
