### ISSUE TITLE
Improvements in EvalAI User Interface

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/GSoC-Ideas#59]
**Project Title:** Improvements in EvalAI User Interface

**Description:** The goal of this project is to improve the overall user experience for challenge hosts and participants on EvalAI by allowing them to tag and filter challenges and creating an intuitive and informative leaderboard. This project will involve creating - a comprehensive search feature to find challenges, a tagging system for different challenge types (ex: Computer Vision, NLP, etc) for categorization. This will help participants and challenge hosts find challenges and search for related ones based on tags.  An improved leaderboard, along with the search feature, will help in streamlining the process of organizing challenges, participating in challenges, and ranking participants. In addition, we will also work on adding support for relevant metadata for each challenge such as prize money, sponsors, etc.

**Deliverable:**

- Search, Filter and Tagging
  - [ ] Add the following attributes to challenges via challenge configuration:
    - Tags such as CV, NLP, RL, etc.
    - Prize Money
    - Sponsors
  - [ ] Implement search functionality in challenges by specific meta information (e.g. title, sponsors, ID, etc.)
  - [ ] Implement frontend changes to display tags on challenge page/gallery.
  - [ ] Implement relevant Django APIs for filtering challenges by tags, date, etc.
  - [ ] Add filter options in search functionality such as by tags, date, etc.
  - [ ] Implement breadcrumbs on frontend and the ability to view challenges based on the tags selected.
  - [ ] Add tests for the search, filter and tagging functionalities.

- Leaderboard
  - [ ] Add a feature to highlight the submission on the “My Submissions” page for the participants which appears on the current leaderboard. 
    - This helps the participants know which of their submissions are currently showing on the leaderboard, i.e. which approach is working the best according to the metric of choice.
  - [ ] Change CSS to crop longer column headings.
  - [ ] Normalize headings in the leaderboard to follow consistent format.

**Mentor:** Gunjan Chhablani, Ram Ramrakhya

**Skills:** Python, Django, AngularJS, AWS

**Skill Level:** Medium

**Get started:** Try to fix some issues in EvalAI (note that there are some issues labeled with GSOC-2023)

**Important Links**:
- EvalAI Website: [eval.ai](https://eval.ai/)
- EvalAI Github repository: [Cloud-CV/EvalAI](https://github.com/Cloud-CV/EvalAI)
- EvalAI Docs: http://evalai.readthedocs.io/en/latest
- GSoC Proposal Template: [Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template](https://github.com/Cloud-CV/GSoC-Ideas/wiki/GSOC-2020-Proposal-Template)
- Gitter Channel: [gitter.im/Cloud-CV](https://gitter.im/Cloud-CV/)
- Mailing list: [groups.google.com/forum/#!forum/cloudcv](https://groups.google.com/forum/#!forum/cloudcv)

**Comment by 123Vasu** [comment]
I would like to work on this @Ram81 for GSOC

**Comment by KrishnaRishi2208** [comment]
I have reviewed the project and I feel that I have sufficient knowledge to implement the features that are required. 

It is given that I can get started by trying to fix issues with GSOC-2023 as a label. But , I have visited the EvalAI github repository and found that there is no issue with GSOC-2023 as a label. Should I start by trying to fix another issue or do I wait until you add issues with GSOC-2023 as labels.

Hoping to hear from you soon.

**Comment by marinicadenisandrei** [comment]
Hi,

I am very interested in participating for the "Improvements in EvalAI User Interface" program offered by GSOC 2023.

I am very passionate about this field, I currently work for companies that use the same technologies and I am also a master's student with a profile focused on these technologies. I would like to interact with a very well developed team, from which I can learn a lot of things and to be able to interact and implement all the knowledge to contribute to this project.

I am very passionate, I want to devote myself a lot to the project and to be able to participate in this GSOC 2023 program.

**Comment by sususama** [comment]
Hi,
My name is Wang Xuhao. I'm a graduate student of software engineering in the School of Computer Science, Xi'an Technology University. 

In mt previous development experience, i have used Java, JavaScript, CSS, HTML5, Python, Pytorch, MySQL, Spring Boot, Git and Vue. I have some web front-end development experience. Although I won't use Angular and Django yet. But I think I have very strong learning ability. I will learn these two technologies before you officially confirm the list.

I hope you can reply to me. I am looking forward to participating in GSoC in Cloud-CV.
My Email:sususama2@163.com

**Comment by Nishant123455** [comment]
hello
 I am Nishant Mishra and I currently a student at Manipal University Jaipur India pursing Information Technology BTech my skills are :-
Python
django 
React.js
c/c++
javascript
react.js
 
I am interested to contribute on this project

**Comment by gchhablani** [comment]
@sususama @KrishnaRishi2208 @Nishant123455 @123Vasu @marinicadenisandrei

Thank you for reaching out to us regarding the Google Summer of Code (GSoC) 2023 program. We appreciate your interest in our project and we are excited to have you as a potential participant.

As you may have seen, we have some open issues that we are looking into for both EvalAI and EvalAI-CLI. You can find them on our Github page at the following links:

- On EvalAI: https://github.com/Cloud-CV/EvalAI/issues?q=is%3Aissue+is%3Aopen+label%3AGSoC-2023
- On EvalAI-CLI: https://github.com/Cloud-CV/evalai-cli/issues/342

We encourage you to experiment with EvalAI and report any issues that you come across. We will be posting more issues soon, so stay tuned for those.

We have a Slack workspace that you can join to connect with other interested participants. Here's the link to join: https://join.slack.com/t/cloudcv-community/shared_invite/zt-1rkm0m8pw-TBkjRjx~_GyIvMVlF5iDHg

Once you're in, you can join the #gsoc-23-interested-participants channel to stay up to date on the latest news and discuss the project with other potential participants.

In the meantime, we encourage you to set up EvalAI locally and continue revising your proposal before the final deadline. If you have any questions or concerns, don't hesitate to reach out to us.

Hi, and welcome to the CloudCV community!

Best regards,

Gunjan Chhablani

**Comment by priyanshmathur** [comment]
Hi,
My name is Priyansh Mathur, and I am in the Pre-final year of my Bachelor's degree in Computer Science and Engineering at PES University, Bengaluru, India. 
I was interested in the integration of Cloud Technologies with AI from the past year after I got more exposure to working with Cloud platforms. 
One of my popular past projects inclined towards the same is Fault tracing of Distributed MicroServices using Jaegar in the Kubernetes Cluster. 
In addition to this, I have also built deep-learning models in the field of computer vision and Image Processing and have a good overall knowledge of the same.
I would like to contribute to your Organization by taking part in the GSOC '23 and helping you build fault-tolerant, efficient and reliable products for your Organization using the skills I have and learning from the experts who are in this field for numerous years.

You can reach out to me through my email id provided below:
mathur.priyansh15@gmail.com

**Comment by tripathi-genius** [comment]
How to contribute for GSoC?

**Comment by gchhablani** [comment]
@priyanshmathur @tripathi-genius 
Please go over this:
https://github.com/Cloud-CV/GSoC-Ideas/issues/59#issuecomment-1477844994

**Comment by 19-ayushi** [comment]
Hi,
I am Ayushi, a third-year computer science student. I am skilled in C, C++, Python, HTML, CSS, JavaScript, and Django.
I am interested in working on the project.
I am looking forward to putting my knowledge and time into this project as well as gaining more experience through the whole process.
Thank you

Regards
Ayushi

**Comment by Shubhamraut01** [comment]
Hello Everyone ,

I am in last year of masters in  Computer Science from Fergusson College , Pune . I have 7 month experience working in Tech Industry . I have underwent AWS training and I will be appearing for certification soon . I have experience in working with ReactJS ,AngularJS ,HTML ,CSS ,Python ,MongoDB , Sql ,git  and Django .I have done a project in which we can create multiple rooms and chat similar to Discord ( link : https://github.com/Shubhamraut01/StuddyBuddy).

I have Knowledge of UI/UX using Figma and Adobe XD . I have done google UX Specialization  here are my UI/UX projects : https://designxt.github.io

I have all the essential Skills required to enhance the UI of the project and enhance its features .

I am looking forward to work on this wonderful project with the CloudCV team / mentors together we can create a better user experience for the users. please checkout my portfolio at :  https//shubhamraut.me to know more .

Thankyou, 
Shubham Raut
shubhamrao12321@gmail.com

**Comment by nickhil-verma** [comment]
Hi,
i just went through EvalAI Github repository and feels that i have sufficient amount of knowledge to improve its user interface 
and went through the issues section found that i am quite efficient to solve all those issue regarded to user interface and i see evalai as my future platform to participate in GSOC 2024 .currently pursuing my B.Tech from DSI | Bengaluru

hoping so you assign me issues and looking for further opportunity with evalai 

Thank You 
Nikhil Verma 
vermanick75@gmail.com
