### ISSUE TITLE
Implementing Popular Deep Learning Architectures in Cloud CV 

### ISSUE THREAD

**Issue by kritkaran94** [Cloud-CV/GSoC-Ideas#6]
**Project Title:** Writing tutorials and implementing popular deep learning architectures in CloudCV 

**Description:** This project involves implementing popular deep learning algorithms and integrating them with the code base of CloudCV. Having said that, this project also aims at developing a
Web-application where users can share their code, discuss about their research work and write  
tutorials .

**Deliverable:** By the end of this project one can expect a web-application which would function as a learning platform to all the members of the computer vision community with the following features :

- It will lay the foundations of a complete repository for prominent deep learning algorithms discussed and enable the computer vision community to invest their time in learning something new rather than implementing the existing algorithms.

- The web application would host source codes for popular deep learning algorithms, provide an interactive platform to the users to view the results of each algorithm along with in-depth tutorial.

To sum up the end-product of this project ie.. a web-application will essentially be a one stop resource where users can find relevant papers, open source code based on those papers, an online demo of that algorithm and a descriptive tutorial on the same.

**Mentor:** Deshraj Yadav (@deshraj), is a suitable mentor as he had been involved in the project when it was proposed  last year as well. Other mentors too can be added ?

**Skills:** 

- Familiarity with containers, javascript, HTML, CSS and PHP would be a big plus.

- Expertise in using python based web-servers like Flask and Django.

- Familiarity with deep learning frameworks like Caffe / Theano / Keras / TensorFlow etc. Students are expected to have played around with these tools and should be familiar with the input / output pipelines.
Familiarity with building multi-threading, multi-processing architectures, and asynchronous operations.
Expertise in Lua (especially Torch framework) to build a similar tool for Torch. This may require building an interface for python-torch communication and the student will have to experiment with various ways since Lua is not as mature as Python in terms of open source web-frameworks.

**Skill Level:**  Medium

**Comment by kritkaran94** [comment]
@deshraj, Sir  I have created this issue. Since, I proposed this project last year as well it would be great If we could discuss more about it and see how this project can be worked upon.

**Comment by deshraj** [comment]
Hi @kritkaran94, thanks for opening this issue. We discussed this idea amongst the team members and we concluded that we won't proceed with this idea. Feel free to work on any other idea matching to your skill set. Looking forward for your contributions.
