### ISSUE TITLE
CloudCV Web App Redesign

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/GSoC-Ideas#7]
**Project Title:** Redesigning CloudCV using React + Django.

https://github.com/Cloud-CV/CloudCV

**Description:** CloudCV main website has a lot of legacy code that needs to be cleaned and needs a complete revamp. The goal of this project is to use best practices for deployment + operations and support all the other infrastructural needs for other projects like EvalAI, IDE, CV-fy etc. 

**Deliverable:** 
- Use React + Material design to build standard components that are shared amongst all the demos.
- Setup CI/CD for CloudCV
- Add integration tests using Selenium
- Add more logging / analytics around each demo so that we can use it later for training new models.
- Add metric logging / error logging in Datadog / Sentry.
- Dockerize the entire CloudCV infrastructure.
- Add support for running some of the demos on Web using javascript based DL frameworks.

**Mentor:** Deshraj Yadav @deshraj / Harsh Agrawal @dexter1691 

**Skills:** React, Python, Django

**Skill Level:** Medium

**Get started**: Take a look at our issues on other Projects. Try to fix some (note that there are some issues labeled with GSOC).

**Comment by iharsh234** [comment]
@dexter1691  since there only one issue on main website , do i suppose to contribute on other repos like EvalAI and IDE. If possible can you assign me one.

**Comment by deshraj** [comment]
@iharsh234 yeah, Please look for other issues on other projects if available. :)

**Comment by Shashi456** [comment]
what other issues can i look at?

**Comment by deshraj** [comment]
@Shashi456 I think your problem is solved now. :)

**Comment by Shashi456** [comment]
@deshraj  yes thankyou , have i now cleared the patch requirement for gsoc can i go about trying to draft my application ?

**Comment by deshraj** [comment]
Yeah please do. :)

**Comment by yadavankit** [comment]
@dexter1691 @deshraj can you please give me an insight into this deliverable -

> Add more logging / analytics around each demo so that we can use it later for training new models.

**Comment by Rebaiahmed** [comment]
@deshraj  i want to contribute to this project , please help me what i should do ?

**Comment by HargovindArora** [comment]
Hello Sir! My key skills are Python and Django and improving further. I wanted to contribute to Cloud-CV. How can I start? 
Thank You!

**Comment by RishabhJain2018** [comment]
Hello @HargovindArora You can get started using our Ideas page http://gsoc.cloudcv.org. To look for the issues you can jump to https://github.com/Cloud-CV.
Feel free to ask any doubt on the respective `gitter` channel. :)

**Comment by HargovindArora** [comment]
Sure Sir. I'll be active on Gitter and now starting to search  for an issue.
Thanks.

**Comment by iteachmachines** [comment]
Sir i am very much interested in contributing in EvalAI can you please guide me about how to get started.And when i see the code i find it tough to understand.

**Comment by RishabhJain2018** [comment]
Hey @iteachmachines In order to get started with EvalAI, try setting up the project on your local machine by following the instructions in `Readme` file. After setting up, the next steps would be to look for the issues in the issues section of the repository or [this](https://github.com/Cloud-CV/EvalAI/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy_to_fix) link for `easy` or `beginner` level issues. Moreover, please let us know if you face any difficulty in setting up the project on the gitter(https://gitter.im/Cloud-CV/EvalAI) channel. I would be glad to help you in getting started. :-)

**Comment by iteachmachines** [comment]
Sure, thank you.
